trigger:
  branches:
    include:
    - develop
    - release
    - main
    - devops
    - devops/*
#  paths:
#    include:
#    - .cdk-infra/*

pr: none

pool:
  name: 'lau-devops'

stages:

- stage: CDKSYNTH
  displayName: "Build CDK"
  jobs:
  - template: azure-pipelines-cdk.yml 
    parameters:
      variablesGroup: 'DEV-UPC-ED.PE-LAU-FE-WETALK'

- stage: BuildDevelop
  displayName: "Build App for Develop"
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      variablesGroup: 'DEV-UPC-ED.PE-LAU-FE-WETALK'

- stage: BuildRelease
  displayName: "Build App for Release"
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release')
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      variablesGroup: 'CERT-UPC-ED.PE-LAU-FE-WETALK'

- stage: BuildMain
  displayName: "Build App for Main"
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      variablesGroup: 'PROD-UPC-ED.PE-LAU-FE-WETALK'