parameters:
- name: variablesGroup
  default: 'ubuntu-latest'
- name: nodeVersion
  default: '20.*'

jobs:
- job:  'npmBUILD'
  displayName: "Build Environment"
  variables:
    - group: ${{parameters.variablesGroup}}
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec:  ${{ parameters.nodeVersion }}  
      addToPath: true
 
  - script: |
      npm install --frozen-lockfile
      npm install --legacy-peer-deps
    displayName: 'Instalar dependencias'
  - script: |      
      npm run generate     
    displayName: 'npm run generate'
    # npm run export   

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '.output/public/' 
      artifact: 'app'   
    displayName: 'Publicar artefacto del directorio public'

  
 