parameters:
- name: variablesGroup
  default: 'ubuntu-latest'
- name: nodeVersion
  default: '16.*'

jobs:
- job:  'npmBUILD'
  displayName: "Build Environment"
  variables:
    - group: ${{parameters.variablesGroup}}
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec:  ${{ parameters.nodeVersion }}  
      addToPath: true
 
  - script: |
      npm install --frozen-lockfile
    displayName: 'Instalar dependencias'

  - script: |      
      npm run build      
    displayName: 'npm build and export'
    # npm run export   

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'dist/' 
      artifact: 'app'   
    displayName: 'Publicar artefacto del directorio public'

  
 